# Generated by Django 2.0.5 on 2018-09-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo',
            new_name='add',
        ),
    ]
