# Generated by Django 2.0.5 on 2018-09-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180904_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add',
            new_name='addd',
        ),
    ]
